### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by Starou** [Starou/django-yaaac#1]
- [x] Works with inlines
- [x] Fix new-inline (ticket #2)
- [ ] Works with M2M
- [x] Tests in admin
- [x] Filter on limit_choices_to (Ajax search, lookup) (btw, filtering on admin.limit_choices_to is not do-able) 
- [ ] dynamic limit_choices_to ?
- [x] move urls calculation from field.**init**() to widget.render()
- [x] rename yaaac_opts["value_attr"] in "search_fields"
- [x] use contenttype name instead of id in search url
- [x] enhance yaaac_opts for autocomplete opts
- [x] README (in-progress)
- [ ] Localize
- [ ] works with composite FK
- [x] PIP release
- [x] allow usage of callable in suggestion
- [ ] select_related()
- [x] search on multiple fields
- [ ] fix resize flickering when show/hide automplete/label.
- [ ] Add `onHover: callback` option.
- [ ] Allow the customization of the search message in the field. Construct the msg from search_fields maybe ?
- [x] Link to `get_absolute_url()`
